plugins:
  discourse_debates_enabled:
    default: false
    client: true
  discourse_debates_suggestion_min_votes:
    default: 10
    client: true
    type: integer
    min: 1
    max: 100
  discourse_debates_suggestion_category_id:
    default: -1
    type: integer
    client: true